#!/usr/bin/env sh
echo "Begining post install setup for AppLock"
chmod +x /opt/applock/AppLock
if [ ! -h /usr/bin/applock ]; then
    ln -s /opt/applock/AppLock /usr/bin/applock
fi
echo "Post Install complete"
echo "Starting AppLock Daemon"
initctl emit AppLockStartDaemon
echo "Daemon Started"
if [ -e /opt/applock/settings.db ]; then
    chmod +rw /opt/applock/settings.db
fi
